---
- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}

- name: Install required packages
  yum:
    name:
      - curl
      - wget
      - vim
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Comment out swap line in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap)'
    replace: '# \1'

- name: Enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl settings
  command: sysctl --system
