---
- name: Common configuration                 # Define the play name
  hosts: all                                 # Apply tasks to all hosts
  become: yes                                # Run tasks with elevated privileges
  tasks:

    - name: Disable swap                     # Task to turn off swap memory
      command: swapoff -a                    # Execute the 'swapoff' command

    - name: Ensure swap is disabled in fstab # Task to prevent swap from enabling on reboot
      replace:
        path: /etc/fstab                     # File where swap configuration is stored
        regexp: '^\s*(.+?)\s+swap\s'         # Regular expression to find swap entries
        replace: '# \1 swap '                # Comment out swap entries

    - name: Disable SELinux                  # Task to disable SELinux
      selinux:
        state: disabled                      # Ensure SELinux is set to 'disabled' mode

    - name: Ensure firewalld is stopped and disabled # Task to stop and disable the firewall
      service:
        name: firewalld                      # Specify the firewall service
        state: stopped                       # Ensure the service is stopped
        enabled: no                          # Ensure the service does not start on boot

    - name: Load necessary kernel modules    # Task to load kernel modules needed by Kubernetes
      modprobe:
        name: "{{ item }}"                   # Specify the module name (loop variable)
        state: present                       # Ensure module is loaded
      loop:
        - overlay                            # Module for filesystem overlay
        - br_netfilter                       # Module for network filtering

    - name: Configure sysctl parameters      # Task to set kernel parameters
      copy:
        dest: /etc/sysctl.d/kubernetes.conf  # File to store configuration
        content: |                           # Configuration content
          net.bridge.bridge-nf-call-ip6tables = 1    # Enable IPv6 packet filtering
          net.bridge.bridge-nf-call-iptables = 1     # Enable IPv4 packet filtering
          net.ipv4.ip_forward = 1                    # Enable packet forwarding

    - name: Apply sysctl parameters          # Task to apply the sysctl settings
      command: sysctl --system               # Reload sysctl settings

    - name: Install essential packages       # Task to install necessary packages
      yum:
        name:
          - curl                             # Command line tool for data transfer
          - wget                             # Network downloader
          - vim                              # Text editor
          - git                              # Version control system
          - net-tools                        # Network management tools
          - unzip                            # Archive extraction tool
          - tar                              # Archive utility
          - containerd                       # Container runtime
        state: present                       # Ensure packages are installed

    - name: Enable and start containerd      # Task to manage the containerd service
      systemd:
        name: containerd                     # Name of the service
        enabled: yes                         # Enable service to start on boot
        state: started                       # Ensure service is running