---
- name: Disable swap
  command: swapoff -a

- name: Ensure swap is disabled in fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*(.+?)\s+swap\s'
    replace: '# \1 swap '

- name: Disable SELinux
  selinux:
    state: disabled

- name: Ensure firewalld is stopped and disabled
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Load necessary kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl parameters
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl parameters
  command: sysctl --system

- name: Install essential packages
  yum:
    name:
      - curl
      - wget
      - vim
      - git
      - net-tools
      - unzip
      - tar
      - containerd
    state: present

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
