#trigger: none                              # Disable automatic triggering of this pipeline (manual or CI-triggered only)

#pool:                                     # Define the VM image for the pipeline agent
#  vmImage: 'ubuntu-latest'                 # Use the latest Ubuntu image

#steps:                                    # Define the sequence of pipeline tasks
#- task: TerraformInstaller@1                # Install the specified version of Terraform
#  inputs:
#    terraformVersion: '1.6.6'                # Version of Terraform to install

#- task: PowerShell@2                        # Run a PowerShell script for deployment and configuration
#  displayName: 'Terraform Apply & Ansible Configuration'  # Friendly name in Azure DevOps UI
#  inputs:
#    filePath: 'scripts/cd.ps1'               # Path to the deployment PowerShell script
#    pwsh: true                              # Use PowerShell Core (pwsh) instead of Windows PowerShell
