#trigger:
#  branches:
#    include:
#      - main

#pool:
#  vmImage: 'ubuntu-latest'

#variables:
#  TF_VAR_owner1: 'Omar Khaled'
#  TF_VAR_owner2: 'Salma Walid'
#  TF_VAR_owner3: 'Mariam Mohsen'
#  tf_version: '1.6.6'

#steps:
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.x'

#- task: TerraformInstaller@1
#  inputs:
#    terraformVersion: '$(tf_version)'

#- task: PowerShell@2
#  displayName: 'Terraform Init & Plan'
#  inputs:
#    filePath: 'scripts/ci.ps1'
#    pwsh: true
