trigger:
- main

variables:
  - group: AWS_Temporary_Credentials

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'windows-latest'
    steps:

    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Set-Location -Path './petclinic'
          npm install
          npm run build
          npm test
      displayName: 'Build and Test'

- stage: StaticCodeAnalysis
  jobs:
  - job: SCA
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQubeServiceConnection'
        projectKey: 'PetClinic'
        projectName: 'Pet Clinic'
        projectVersion: '1.0'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Set-Location -Path './petclinic'
          npm install
          sonar-scanner -Dsonar.projectKey="PetClinic" -Dsonar.sources="."
      displayName: 'Run SonarQube Analysis'

    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'