---
- name: Enable containerd
  systemd:
    name: containerd
    state: started
    enabled: true

- name: Fetch join command from master
  command: cat /tmp/kube_join.sh
  register: join_command
  delegate_to: master

- name: Join Kubernetes cluster
  command: "{{ join_command.stdout }}"
