---
- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: no

- name: Install Kubernetes components
  yum:
    name:
      - kubeadm-{{ kube_version }}
      - kubelet-{{ kube_version }}
      - kubectl-{{ kube_version }}
    state: present
    disable_gpg_check: yes

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: Copy join script from master
  fetch:
    src: /tmp/join.sh
    dest: /tmp/join.sh
    flat: yes
  delegate_to: master

- name: Run join command
  command: sh /tmp/join.sh

