---
- name: Add Kubernetes YUM repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}/rpm/"
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_search('^\\d+\\.\\d+') }}/rpm/repodata/repomd.xml.key
      
- name: Install Kubernetes components
  yum:
    name:
      - kubeadm-{{ kube_version }}
      - kubelet-{{ kube_version }}
      - kubectl-{{ kube_version }}
    state: present
    disable_gpg_check: yes

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: Copy join script from master
  fetch:
    src: /tmp/join.sh
    dest: /tmp/join.sh
    flat: yes
  delegate_to: master

- name: Run join command
  command: sh /tmp/join.sh

