---
- name: Common setup on all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Master node setup
  hosts: master
  become: yes
  roles:
    - master

- name: Worker node setup
  hosts: worker
  become: yes
  roles:
    - worker
