---
- name: Common setup on all nodes              # Playbook for common setup on all nodes
  hosts: all                                   # Apply to all hosts
  become: yes                                  # Run tasks with elevated privileges
  roles:
    - common                                   # Apply the 'common' role

- name: Kubernetes master setup                # Playbook for setting up Kubernetes master
  hosts: master                                # Apply to master nodes
  become: yes                                  # Run tasks with elevated privileges
  roles:
    - master                                   # Apply the 'master' role

- name: Kubernetes worker setup                # Playbook for setting up Kubernetes workers
  hosts: worker                                # Apply to worker nodes
  become: yes                                  # Run tasks with elevated privileges
  roles:
    - worker                                   # Apply the 'worker' role