apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-db
  template:
    metadata:
      labels:
        app: sql-db
    spec:
      containers:
      - name: db-container
        image: mydbimage:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: sql-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP