---
- name: Initialize Kubernetes Master
  command: kubeadm init --apiserver-advertise-address=192.168.56.10 --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Pause after kubeadm init to wait for control plane components
  pause:
    seconds: 20

- name: Set up kube config for root
  shell: |
    sudo mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: flannel_result
  until: flannel_result.rc == 0
  retries: 5
  delay: 10

- name: Wait for kube-flannel pod to be ready
  shell: |
    kubectl wait --for=condition=Ready pod -l app=flannel -n kube-flannel --timeout=180s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: wait_result
  until: wait_result.rc == 0
  retries: 3
  delay: 15

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Save join command to file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /join.sh
    mode: '0755'

- name: Output join command for debug
  debug:
    msg: "Join command: {{ join_command.stdout }}"
