---
- name: Add Kubernetes YUM repo
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_search('^\\d+\\.\\d+') }}/rpm/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_search('^\\d+\\.\\d+') }}/rpm/repodata/repomd.xml.key

- name: Install Kubernetes components
  yum:
    name:
      - kubeadm-{{ kube_version }}
      - kubelet-{{ kube_version }}
      - kubectl-{{ kube_version }}
    state: present
    disable_gpg_check: yes

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes

- name: Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: Save join command
  shell: |
    kubeadm token create --print-join-command > /tmp/join.sh
  when: kubeadm_init is changed

- name: Create kube config for ec2-user
  become_user: ec2-user
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Flannel CNI plugin
  become_user: ec2-user
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
